version: '2'
services:
  sshd_1:
    image: rastasheep/ubuntu-sshd:18.04
    container_name: sshd-1
    networks:
      static-network:
        ipv4_address: 172.20.128.2
  sshd_2:
    image: rastasheep/ubuntu-sshd:18.04
    container_name: sshd-2
    networks:
      static-network:
        ipv4_address: 172.20.128.3
  sshd_3:
    image: rastasheep/ubuntu-sshd:18.04
    container_name: sshd-3
    networks:
      static-network:
        ipv4_address: 172.20.128.4
networks:
  static-network:
    ipam:
      config:
        - subnet: 172.20.0.0/16
          #docker-compose v3+ do not use ip_range
          ip_range: 172.28.5.0/24
