-
    name: 'Execute pipeline ksql and ksql-udf'
    hosts: ksql_servers
    tasks:
        -
            name: 'Extract .zip in /temp/{{ name_directory }}'
            ansible.builtin.unarchive:
              src: '{{ name_file }}'
              dest: '/temp/{{ name_directory }}'
        -
            name: Find files .jar
            find:
              paths: '/temp/{{ name_directory }}'
              patterns: '*.jar'
            register: output
        -
            name: Find files .ksql
            find:
              paths: '/temp/{{ name_directory }}'
              patterns: '*.ksql'
            register: outputk
        -
            name: Ansible copy multiple files with wildcard matching *.jar to KSQL servers.
            copy:
              src: "{{ item }}"
              dest: /opt/ksql-extension/
              owner: cp-ksql
              group: confluent
              mode: 0755
              force: yes
            with_fileglob:
              - '/temp/{{ name_directory }}/*.jar'
            when: output.matched == 1

        -
            name: 'reboot clusters KSQL'
            when: output.matched == 1
        -
            name: 'Execute a script or curl gainst KSQL api'
            script: /tmp/install_script.sh
            when: outputk.matched == 1
        -
            name: 'delete directory'
            file:
              state: absent
              path: "/temp/{{ name_directory }}/"
